# Generated by Django 4.0.4 on 2022-08-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mang_xa_hoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
