# Generated by Django 4.0.4 on 2022-09-05 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mang_xa_hoi', '0002_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='post_img')),
                ('caption', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('liked', models.IntegerField(default=0)),
            ],
        ),
    ]
