# Generated by Django 4.0.4 on 2022-09-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mang_xa_hoi', '0005_alter_likepost_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('friend', models.CharField(max_length=100)),
            ],
        ),
    ]
